# Generated by Django 4.0.3 on 2022-04-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relacion', models.IntegerField(verbose_name='relacion')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombre')),
                ('edad', models.CharField(max_length=50, verbose_name='edad')),
                ('cumpleagnos', models.CharField(max_length=8, verbose_name='cumpleagnos')),
            ],
        ),
    ]
