# Generated by Django 4.0.3 on 2022-04-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FamiliaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familia',
            name='relacion',
            field=models.CharField(max_length=50, verbose_name='relacion'),
        ),
    ]
